INSERT INTO Pais VALUES(1, 'AF', 'Afganistán');
INSERT INTO Pais VALUES(2, 'AX', 'Islas Gland');
INSERT INTO Pais VALUES(3, 'AL', 'Albania');
INSERT INTO Pais VALUES(4, 'DE', 'Alemania');
INSERT INTO Pais VALUES(5, 'AD', 'Andorra');
INSERT INTO Pais VALUES(6, 'AO', 'Angola');
INSERT INTO Pais VALUES(7, 'AI', 'Anguilla');
INSERT INTO Pais VALUES(8, 'AQ', 'Antártida');
INSERT INTO Pais VALUES(9, 'AG', 'Antigua y Barbuda');
INSERT INTO Pais VALUES(10, 'AN', 'Antillas Holandesas');
INSERT INTO Pais VALUES(11, 'SA', 'Arabia Saudí');
INSERT INTO Pais VALUES(12, 'DZ', 'Argelia');
INSERT INTO Pais VALUES(13, 'AR', 'Argentina');
INSERT INTO Pais VALUES(14, 'AM', 'Armenia');
INSERT INTO Pais VALUES(15, 'AW', 'Aruba');
INSERT INTO Pais VALUES(16, 'AU', 'Australia');
INSERT INTO Pais VALUES(17, 'AT', 'Austria');
INSERT INTO Pais VALUES(18, 'AZ', 'Azerbaiyán');
INSERT INTO Pais VALUES(19, 'BS', 'Bahamas');
INSERT INTO Pais VALUES(20, 'BH', 'Bahréin');
INSERT INTO Pais VALUES(21, 'BD', 'Bangladesh');
INSERT INTO Pais VALUES(22, 'BB', 'Barbados');
INSERT INTO Pais VALUES(23, 'BY', 'Bielorrusia');
INSERT INTO Pais VALUES(24, 'BE', 'Bélgica');
INSERT INTO Pais VALUES(25, 'BZ', 'Belice');
INSERT INTO Pais VALUES(26, 'BJ', 'Benin');
INSERT INTO Pais VALUES(27, 'BM', 'Bermudas');
INSERT INTO Pais VALUES(28, 'BT', 'Bhután');
INSERT INTO Pais VALUES(29, 'BO', 'Bolivia');
INSERT INTO Pais VALUES(30, 'BA', 'Bosnia y Herzegovina');
INSERT INTO Pais VALUES(31, 'BW', 'Botsuana');
INSERT INTO Pais VALUES(32, 'BV', 'Isla Bouvet');
INSERT INTO Pais VALUES(33, 'BR', 'Brasil');
INSERT INTO Pais VALUES(34, 'BN', 'Brunéi');
INSERT INTO Pais VALUES(35, 'BG', 'Bulgaria');
INSERT INTO Pais VALUES(36, 'BF', 'Burkina Faso');
INSERT INTO Pais VALUES(37, 'BI', 'Burundi');
INSERT INTO Pais VALUES(38, 'CV', 'Cabo Verde');
INSERT INTO Pais VALUES(39, 'KY', 'Islas Caimán');
INSERT INTO Pais VALUES(40, 'KH', 'Camboya');
INSERT INTO Pais VALUES(41, 'CM', 'Camerún');
INSERT INTO Pais VALUES(42, 'CA', 'Canadá');
INSERT INTO Pais VALUES(43, 'CF', 'República Centroafricana');
INSERT INTO Pais VALUES(44, 'TD', 'Chad');
INSERT INTO Pais VALUES(45, 'CZ', 'República Checa');
INSERT INTO Pais VALUES(46, 'CL', 'Chile');
INSERT INTO Pais VALUES(47, 'CN', 'China');
INSERT INTO Pais VALUES(48, 'CY', 'Chipre');
INSERT INTO Pais VALUES(49, 'CX', 'Isla de Navidad');
INSERT INTO Pais VALUES(50, 'VA', 'Ciudad del Vaticano');
INSERT INTO Pais VALUES(51, 'CC', 'Islas Cocos');
INSERT INTO Pais VALUES(52, 'CO', 'Colombia');
INSERT INTO Pais VALUES(53, 'KM', 'Comoras');
INSERT INTO Pais VALUES(54, 'CD', 'República Democrática del Congo');
INSERT INTO Pais VALUES(55, 'CG', 'Congo');
INSERT INTO Pais VALUES(56, 'CK', 'Islas Cook');
INSERT INTO Pais VALUES(57, 'KP', 'Corea del Norte');
INSERT INTO Pais VALUES(58, 'KR', 'Corea del Sur');
INSERT INTO Pais VALUES(59, 'CI', 'Costa de Marfil');
INSERT INTO Pais VALUES(60, 'CR', 'Costa Rica');
INSERT INTO Pais VALUES(61, 'HR', 'Croacia');
INSERT INTO Pais VALUES(62, 'CU', 'Cuba');
INSERT INTO Pais VALUES(63, 'DK', 'Dinamarca');
INSERT INTO Pais VALUES(64, 'DM', 'Dominica');
INSERT INTO Pais VALUES(65, 'DO', 'República Dominicana');
INSERT INTO Pais VALUES(66, 'EC', 'Ecuador');
INSERT INTO Pais VALUES(67, 'EG', 'Egipto');
INSERT INTO Pais VALUES(68, 'SV', 'El Salvador');
INSERT INTO Pais VALUES(69, 'AE', 'Emiratos Árabes Unidos');
INSERT INTO Pais VALUES(70, 'ER', 'Eritrea');
INSERT INTO Pais VALUES(71, 'SK', 'Eslovaquia');
INSERT INTO Pais VALUES(72, 'SI', 'Eslovenia');
INSERT INTO Pais VALUES(73, 'ES', 'España');
INSERT INTO Pais VALUES(74, 'UM', 'Islas ultramarinas de Estados Unidos');
INSERT INTO Pais VALUES(75, 'US', 'Estados Unidos');
INSERT INTO Pais VALUES(76, 'EE', 'Estonia');
INSERT INTO Pais VALUES(77, 'ET', 'Etiopía');
INSERT INTO Pais VALUES(78, 'FO', 'Islas Feroe');
INSERT INTO Pais VALUES(79, 'PH', 'Filipinas');
INSERT INTO Pais VALUES(80, 'FI', 'Finlandia');
INSERT INTO Pais VALUES(81, 'FJ', 'Fiyi');
INSERT INTO Pais VALUES(82, 'FR', 'Francia');
INSERT INTO Pais VALUES(83, 'GA', 'Gabón');
INSERT INTO Pais VALUES(84, 'GM', 'Gambia');
INSERT INTO Pais VALUES(85, 'GE', 'Georgia');
INSERT INTO Pais VALUES(86, 'GS', 'Islas Georgias del Sur y Sandwich del Sur');
INSERT INTO Pais VALUES(87, 'GH', 'Ghana');
INSERT INTO Pais VALUES(88, 'GI', 'Gibraltar');
INSERT INTO Pais VALUES(89, 'GD', 'Granada');
INSERT INTO Pais VALUES(90, 'GR', 'Grecia');
INSERT INTO Pais VALUES(91, 'GL', 'Groenlandia');
INSERT INTO Pais VALUES(92, 'GP', 'Guadalupe');
INSERT INTO Pais VALUES(93, 'GU', 'Guam');
INSERT INTO Pais VALUES(94, 'GT', 'Guatemala');
INSERT INTO Pais VALUES(95, 'GF', 'Guayana Francesa');
INSERT INTO Pais VALUES(96, 'GN', 'Guinea');
INSERT INTO Pais VALUES(97, 'GQ', 'Guinea Ecuatorial');
INSERT INTO Pais VALUES(98, 'GW', 'Guinea-Bissau');
INSERT INTO Pais VALUES(99, 'GY', 'Guyana');
INSERT INTO Pais VALUES(100, 'HT', 'Haití');
INSERT INTO Pais VALUES(101, 'HM', 'Islas Heard y McDonald');
INSERT INTO Pais VALUES(102, 'HN', 'Honduras');
INSERT INTO Pais VALUES(103, 'HK', 'Hong Kong');
INSERT INTO Pais VALUES(104, 'HU', 'Hungría');
INSERT INTO Pais VALUES(105, 'IN', 'India');
INSERT INTO Pais VALUES(106, 'ID', 'Indonesia');
INSERT INTO Pais VALUES(107, 'IR', 'Irán');
INSERT INTO Pais VALUES(108, 'IQ', 'Iraq');
INSERT INTO Pais VALUES(109, 'IE', 'Irlanda');
INSERT INTO Pais VALUES(110, 'IS', 'Islandia');
INSERT INTO Pais VALUES(111, 'IL', 'Israel');
INSERT INTO Pais VALUES(112, 'IT', 'Italia');
INSERT INTO Pais VALUES(113, 'JM', 'Jamaica');
INSERT INTO Pais VALUES(114, 'JP', 'Japón');
INSERT INTO Pais VALUES(115, 'JO', 'Jordania');
INSERT INTO Pais VALUES(116, 'KZ', 'Kazajstán');
INSERT INTO Pais VALUES(117, 'KE', 'Kenia');
INSERT INTO Pais VALUES(118, 'KG', 'Kirguistán');
INSERT INTO Pais VALUES(119, 'KI', 'Kiribati');
INSERT INTO Pais VALUES(120, 'KW', 'Kuwait');
INSERT INTO Pais VALUES(121, 'LA', 'Laos');
INSERT INTO Pais VALUES(122, 'LS', 'Lesotho');
INSERT INTO Pais VALUES(123, 'LV', 'Letonia');
INSERT INTO Pais VALUES(124, 'LB', 'Líbano');
INSERT INTO Pais VALUES(125, 'LR', 'Liberia');
INSERT INTO Pais VALUES(126, 'LY', 'Libia');
INSERT INTO Pais VALUES(127, 'LI', 'Liechtenstein');
INSERT INTO Pais VALUES(128, 'LT', 'Lituania');
INSERT INTO Pais VALUES(129, 'LU', 'Luxemburgo');
INSERT INTO Pais VALUES(130, 'MO', 'Macao');
INSERT INTO Pais VALUES(131, 'MK', 'ARY Macedonia');
INSERT INTO Pais VALUES(132, 'MG', 'Madagascar');
INSERT INTO Pais VALUES(133, 'MY', 'Malasia');
INSERT INTO Pais VALUES(134, 'MW', 'Malawi');
INSERT INTO Pais VALUES(135, 'MV', 'Maldivas');
INSERT INTO Pais VALUES(136, 'ML', 'Malí');
INSERT INTO Pais VALUES(137, 'MT', 'Malta');
INSERT INTO Pais VALUES(138, 'FK', 'Islas Malvinas');
INSERT INTO Pais VALUES(139, 'MP', 'Islas Marianas del Norte');
INSERT INTO Pais VALUES(140, 'MA', 'Marruecos');
INSERT INTO Pais VALUES(141, 'MH', 'Islas Marshall');
INSERT INTO Pais VALUES(142, 'MQ', 'Martinica');
INSERT INTO Pais VALUES(143, 'MU', 'Mauricio');
INSERT INTO Pais VALUES(144, 'MR', 'Mauritania');
INSERT INTO Pais VALUES(145, 'YT', 'Mayotte');
INSERT INTO Pais VALUES(146, 'MX', 'México');
INSERT INTO Pais VALUES(147, 'FM', 'Micronesia');
INSERT INTO Pais VALUES(148, 'MD', 'Moldavia');
INSERT INTO Pais VALUES(149, 'MC', 'Mónaco');
INSERT INTO Pais VALUES(150, 'MN', 'Mongolia');
INSERT INTO Pais VALUES(151, 'MS', 'Montserrat');
INSERT INTO Pais VALUES(152, 'MZ', 'Mozambique');
INSERT INTO Pais VALUES(153, 'MM', 'Myanmar');
INSERT INTO Pais VALUES(154, 'NA', 'Namibia');
INSERT INTO Pais VALUES(155, 'NR', 'Nauru');
INSERT INTO Pais VALUES(156, 'NP', 'Nepal');
INSERT INTO Pais VALUES(157, 'NI', 'Nicaragua');
INSERT INTO Pais VALUES(158, 'NE', 'Níger');
INSERT INTO Pais VALUES(159, 'NG', 'Nigeria');
INSERT INTO Pais VALUES(160, 'NU', 'Niue');
INSERT INTO Pais VALUES(161, 'NF', 'Isla Norfolk');
INSERT INTO Pais VALUES(162, 'NO', 'Noruega');
INSERT INTO Pais VALUES(163, 'NC', 'Nueva Caledonia');
INSERT INTO Pais VALUES(164, 'NZ', 'Nueva Zelanda');
INSERT INTO Pais VALUES(165, 'OM', 'Omán');
INSERT INTO Pais VALUES(166, 'NL', 'Países Bajos');
INSERT INTO Pais VALUES(167, 'PK', 'Pakistán');
INSERT INTO Pais VALUES(168, 'PW', 'Palau');
INSERT INTO Pais VALUES(169, 'PS', 'Palestina');
INSERT INTO Pais VALUES(170, 'PA', 'Panamá');
INSERT INTO Pais VALUES(171, 'PG', 'Papúa Nueva Guinea');
INSERT INTO Pais VALUES(172, 'PY', 'Paraguay');
INSERT INTO Pais VALUES(173, 'PE', 'Perú');
INSERT INTO Pais VALUES(174, 'PN', 'Islas Pitcairn');
INSERT INTO Pais VALUES(175, 'PF', 'Polinesia Francesa');
INSERT INTO Pais VALUES(176, 'PL', 'Polonia');
INSERT INTO Pais VALUES(177, 'PT', 'Portugal');
INSERT INTO Pais VALUES(178, 'PR', 'Puerto Rico');
INSERT INTO Pais VALUES(179, 'QA', 'Qatar');
INSERT INTO Pais VALUES(180, 'GB', 'Reino Unido');
INSERT INTO Pais VALUES(181, 'RE', 'Reunión');
INSERT INTO Pais VALUES(182, 'RW', 'Ruanda');
INSERT INTO Pais VALUES(183, 'RO', 'Rumania');
INSERT INTO Pais VALUES(184, 'RU', 'Rusia');
INSERT INTO Pais VALUES(185, 'EH', 'Sahara Occidental');
INSERT INTO Pais VALUES(186, 'SB', 'Islas Salomón');
INSERT INTO Pais VALUES(187, 'WS', 'Samoa');
INSERT INTO Pais VALUES(188, 'AS', 'Samoa Americana');
INSERT INTO Pais VALUES(189, 'KN', 'San Cristóbal y Nevis');
INSERT INTO Pais VALUES(190, 'SM', 'San Marino');
INSERT INTO Pais VALUES(191, 'PM', 'San Pedro y Miquelón');
INSERT INTO Pais VALUES(192, 'VC', 'San Vicente y las Granadinas');
INSERT INTO Pais VALUES(193, 'SH', 'Santa Helena');
INSERT INTO Pais VALUES(194, 'LC', 'Santa Lucía');
INSERT INTO Pais VALUES(195, 'ST', 'Santo Tomé y Príncipe');
INSERT INTO Pais VALUES(196, 'SN', 'Senegal');
INSERT INTO Pais VALUES(197, 'CS', 'Serbia y Montenegro');
INSERT INTO Pais VALUES(198, 'SC', 'Seychelles');
INSERT INTO Pais VALUES(199, 'SL', 'Sierra Leona');
INSERT INTO Pais VALUES(200, 'SG', 'Singapur');
INSERT INTO Pais VALUES(201, 'SY', 'Siria');
INSERT INTO Pais VALUES(202, 'SO', 'Somalia');
INSERT INTO Pais VALUES(203, 'LK', 'Sri Lanka');
INSERT INTO Pais VALUES(204, 'SZ', 'Suazilandia');
INSERT INTO Pais VALUES(205, 'ZA', 'Sudáfrica');
INSERT INTO Pais VALUES(206, 'SD', 'Sudán');
INSERT INTO Pais VALUES(207, 'SE', 'Suecia');
INSERT INTO Pais VALUES(208, 'CH', 'Suiza');
INSERT INTO Pais VALUES(209, 'SR', 'Surinam');
INSERT INTO Pais VALUES(210, 'SJ', 'Svalbard y Jan Mayen');
INSERT INTO Pais VALUES(211, 'TH', 'Tailandia');
INSERT INTO Pais VALUES(212, 'TW', 'Taiwán');
INSERT INTO Pais VALUES(213, 'TZ', 'Tanzania');
INSERT INTO Pais VALUES(214, 'TJ', 'Tayikistán');
INSERT INTO Pais VALUES(215, 'IO', 'Territorio Británico del Océano Índico');
INSERT INTO Pais VALUES(216, 'TF', 'Territorios Australes Franceses');
INSERT INTO Pais VALUES(217, 'TL', 'Timor Oriental');
INSERT INTO Pais VALUES(218, 'TG', 'Togo');
INSERT INTO Pais VALUES(219, 'TK', 'Tokelau');
INSERT INTO Pais VALUES(220, 'TO', 'Tonga');
INSERT INTO Pais VALUES(221, 'TT', 'Trinidad y Tobago');
INSERT INTO Pais VALUES(222, 'TN', 'Túnez');
INSERT INTO Pais VALUES(223, 'TC', 'Islas Turcas y Caicos');
INSERT INTO Pais VALUES(224, 'TM', 'Turkmenistán');
INSERT INTO Pais VALUES(225, 'TR', 'Turquía');
INSERT INTO Pais VALUES(226, 'TV', 'Tuvalu');
INSERT INTO Pais VALUES(227, 'UA', 'Ucrania');
INSERT INTO Pais VALUES(228, 'UG', 'Uganda');
INSERT INTO Pais VALUES(229, 'UY', 'Uruguay');
INSERT INTO Pais VALUES(230, 'UZ', 'Uzbekistán');
INSERT INTO Pais VALUES(231, 'VU', 'Vanuatu');
INSERT INTO Pais VALUES(232, 'VE', 'Venezuela');
INSERT INTO Pais VALUES(233, 'VN', 'Vietnam');
INSERT INTO Pais VALUES(234, 'VG', 'Islas Vírgenes Británicas');
INSERT INTO Pais VALUES(235, 'VI', 'Islas Vírgenes de los Estados Unidos');
INSERT INTO Pais VALUES(236, 'WF', 'Wallis y Futuna');
INSERT INTO Pais VALUES(237, 'YE', 'Yemen');
INSERT INTO Pais VALUES(238, 'DJ', 'Yibuti');
INSERT INTO Pais VALUES(239, 'ZM', 'Zambia');
INSERT INTO Pais VALUES(240, 'ZW', 'Zimbabue');
